gnerv7
gnerv8
launching jobs on gnerv7, in total 2 nodes
launching jobs on gnerv8, in total 2 nodes
0 2 gnerv7
1 2 gnerv7
Process Process-4:
Process Process-1:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:22441: Connection refused
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:7076: Connection refused
Going to initialize rank 4 with world size 8
Going to initialize rank 5 with world size 8
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:43398: Connection refused
Going to initialize rank 7 with world size 8
Process Process-2:
Process Process-3:
Process Process-4:
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:23443: Connection refused
Going to initialize rank 1 with world size 8
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:23957: Connection refused
Going to initialize rank 2 with world size 8
Traceback (most recent call last):
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared_ssd_storage/jingjichen/Mithril_MultiGPU/dgl/main.py", line 23, in init_process
    dist.init_process_group(backend, rank=rank, world_size=size)
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/shared_ssd_storage/jingjichen/anaconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.1.1]:912: Connection refused
Going to initialize rank 3 with world size 8
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd-gnerv7: error: *** JOB 3523 ON gnerv7 CANCELLED AT 2023-09-17T16:24:27 DUE TO TIME LIMIT ***
slurmstepd-gnerv7: error: *** STEP 3523.1 ON gnerv7 CANCELLED AT 2023-09-17T16:24:27 DUE TO TIME LIMIT ***
